### ISSUE TITLE
AttributeError: ("'NoneType' object has no attribute

### ISSUE THREAD

**Issue by rkhemka24** [ContainerSolutions/locust_exporter#32]
I am running command python locust_exporter.py 1234 localhost:8089 and when I open the url localhost:1234 in the browser then I am getting the following error :
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 118, in prometheus_app
    status, header, output = _bake_output(registry, accept_header, params)
  File "/Users/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 100, in _bake_output
    output = encoder(registry)
  File "/Users/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 202, in generate_latest
    output.append(sample_line(s))
  File "/Users/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 159, in sample_line
    ['{}="{}"'.format(
  File "/Users/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 160, in <listcomp>
    k, v.replace('\\', r'\\').replace('\n', r'\n').replace('"', r'\"'))
AttributeError: ("'NoneType' object has no attribute 'replace'", Metric(locust_requests_avg_content_length, Locust requests avg_content_length, gauge, , [Sample(name='locust_requests_avg_content_length', labels={'path': '/hello/world', 'method': 'POST'}, value=165.0, timestamp=None, exemplar=None), Sample(name='locust_requests_avg_content_length', labels={'path': 'Aggregated', 'method': None}, value=165.0, timestamp=None, exemplar=None)]))

Please help me to figure out the issue

**Comment by rkhemka24** [comment]
Issues resolved , it was Issue with the locust_exporter I was using . Closing the issue
